name: Daily Ranking (Tech Books)

on:
  schedule:
    - cron: "10 19 * * *"   # JST 04:10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm i

      - name: Build collector (ts -> js)
        run: npx tsc -p tsconfig.collect.json

      - name: Collect (tech books)
        env:
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}
          QIITA_PAGES: 3
        run: node dist/scripts/collect-tech.js

      - name: Commit if changed
        run: |
          if [ -n "$(git status --porcelain app/data/ranking.json)" ]; then
            git config user.name "actions-bot"
            git config user.email "actions-bot@example.com"
            git add app/data/ranking.json
            git commit -m "chore(data): update ranking.json [skip ci]"
            git push
          else
            echo "No changes."
          fi
