name: Daily Ranking (Tech Books)

on:
  schedule:
    # GitHub Actions は UTC。JST 04:10 = 前日 19:10 UTC
    - cron: "10 19 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci || npm i

      - name: Check source exists (debug)
        run: |
          echo "== pwd ==" && pwd
          echo "== ls scripts ==" && ls -al scripts || true
          test -f scripts/collect-tech.fixed.ts

      - name: Collect (tech books) via tsx
        env:
  MIN_LIKES: '3'
  QIITA_PAGES: '10'MIN_LIKES: '5'
  QIITA_PAGES: '5'
          QIITA_TOKEN: ${{ secrets.QIITA_TOKEN }}   # 任意

        run: npx --yes tsx@^4 scripts/collect-tech.fixed.ts

      - name: Commit if changed
        run: |
          if [ -n "$(git status --porcelain app/data/ranking.json)" ]; then
            git config user.name "actions-bot"
            git config user.email "actions-bot@example.com"
            git add app/data/ranking.json
            git commit -m "chore(data): update ranking.json [skip ci]"
            git push
          else
            echo "No changes."
          fi

      - name: Trigger Vercel deploy (optional)
        if: ${{ env.HOOK != '' }}
        env:
  MIN_LIKES: '3'
  QIITA_PAGES: '10'MIN_LIKES: '5'
  QIITA_PAGES: '5'
          HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
        run: curl -X POST "$HOOK" || true


